name: provider_calculator_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  math_expressions: ^2.3.1
  function_tree: ^0.8.13
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/calculator_logo.png"
  remove_alpha_ios: true # Ensure this is included to remove alpha channel for iOS

flutter:
  uses-material-design: true

  assets:
    - assets/icons/calculator_logo.png
